/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnalysisCard: typeof import('./src/components/AnalysisCard.vue')['default']
    AnswerSheet: typeof import('./src/components/AnswerSheet.vue')['default']
    CountdownTimer: typeof import('./src/components/CountdownTimer.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    OptionItem: typeof import('./src/components/OptionItem.vue')['default']
    PcDesktopSidebarLeft: typeof import('./src/components/PcDesktopSidebarLeft.vue')['default']
    PcDesktopSidebarRight: typeof import('./src/components/PcDesktopSidebarRight.vue')['default']
    QuestionCard: typeof import('./src/components/QuestionCard.vue')['default']
    QuizFooter: typeof import('./src/components/QuizFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubjectPicker: typeof import('./src/components/SubjectPicker.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
